# Generated by Django 2.1.3 on 2018-12-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20181202_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='User_id',
            new_name='User_Email',
        ),
    ]
