# Generated by Django 2.1.3 on 2018-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0008_auto_20181217_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.CharField(max_length=110)),
                ('Post', models.CharField(max_length=11)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
