# Generated by Django 2.1.3 on 2018-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0009_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='Status',
            field=models.BooleanField(default='1'),
        ),
    ]
