# Generated by Django 2.1.3 on 2018-12-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0011_auto_20181218_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='Status',
            field=models.BooleanField(),
        ),
    ]
