# Generated by Django 2.1.3 on 2019-01-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0012_auto_20181220_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.CharField(max_length=100)),
                ('ArticleTitle', models.CharField(max_length=50)),
                ('Article', models.CharField(max_length=2000)),
                ('Deleted', models.BooleanField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
