# Generated by Django 2.1.3 on 2019-02-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0013_auto_20190131_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='LikesDisLikes',
        ),
        migrations.RenameModel(
            old_name='Articles',
            new_name='Posts',
        ),
        migrations.RenameField(
            model_name='likesdislikes',
            old_name='Post',
            new_name='Post_id',
        ),
    ]
