# Generated by Django 2.1.3 on 2019-02-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0014_auto_20190201_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_id', models.IntegerField(max_length=15)),
                ('User_Email', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
