# Generated by Django 2.1.3 on 2019-02-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0016_auto_20190204_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
