# Generated by Django 2.1.3 on 2018-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_users_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='users',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password.html',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='Picture',
            field=models.CharField(default='None', max_length=110),
        ),
    ]
