# Generated by Django 2.1.3 on 2019-01-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_auto_20181202_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Password.html',
        ),
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Name',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='Picture',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
