# Generated by Django 2.1.3 on 2019-02-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_auto_20190131_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Activate',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='users',
            name='Deleted',
            field=models.BooleanField(default='0'),
        ),
    ]
