# Generated by Django 2.1.3 on 2019-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_auto_20190201_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.CharField(default='None', max_length=100)),
                ('Notification_Type', models.IntegerField(max_length=1)),
                ('Message', models.CharField(max_length=300)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
