# Generated by Django 2.1.3 on 2019-02-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='Notification_Type',
            new_name='Type',
        ),
    ]
