# Generated by Django 2.1.3 on 2019-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_auto_20190204_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='See',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='Type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='Activate',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='Deleted',
            field=models.BooleanField(default=0),
        ),
    ]
