# Generated by Django 2.1.3 on 2018-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Post',
            field=models.CharField(max_length=2050),
        ),
    ]
