# Generated by Django 2.1.3 on 2018-12-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20181202_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='User_Email',
            field=models.CharField(max_length=110),
        ),
    ]
